services:
  backend:
    build: ./backend
    env_file:
      - ".env"
    ports:
      - 42069:42069
    depends_on:
      db:
        condition:
          service_healthy
      llm:
        condition:
          service_started

    networks:
      - network

  tramwai:
    build:
      context: .
      dockerfile: ./tramwai/Dockerfile
    env_file:
      - ".env"
    networks:
      - network

  llm:
    build: ./llm
    ports:
      - 11434:11434
    depends_on:
      tramwai:
        condition:
          service_started

    networks:
      - network

  db:
    build: ./db
    restart: always
    env_file:
      - ".env"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=main
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres

    networks:
      - network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432"]
      interval: 3s
      timeout: 6s
      retries: 10

networks:
  network:
